--- 
id: solidityprincipiantes
name: Solidity Principiantes
summary: Curso para principiantes de Solidity basado en los populares contratos de https://solidity-by-example.org/
level: 1
tags: 
  - Solidity