--- 
id: tokenCourse
name: Solidity Token Course
summary: Learn how to create your own ERC20 and NFT tokens. Developed by the p2p learning platform https://dacade.org.
level: 1
tags: 
  - Solidity
  - Tokens
steps:
  - name: 1. Introduction
    path: introduction
  - name: 2.1 ERC20 - Interface
    path: erc20-interface
  - name: 2.2 ERC20 - Token Creation
    path: erc20-token-creation
  - name: 2.3 ERC20 - Interaction
    path: erc20-interaction
  - name: 2.4 ERC20 - Testnet Deployment
    path: erc20-testnet-deployment
  - name: 2.5 ERC20 - Extensions
    path: erc20-extensions
  - name: 3.1 ERC721 - Interface
    path: erc721-interface
  - name: 3.2 ERC721 - Metadata Interface
    path: erc721-interface-metadata
  - name: 3.3 ERC721 - Token Creation
    path: erc721-token-creation
  - name: 3.4 ERC721 - Metadata IPFS
    path: erc721-metadata-ipfs
  - name: 3.5 ERC721 - Deploy Testnet OpenSea
    path: erc721-deploy-testnet-opensea
  - name: 4.1 ERC721 Auction - Contract Setup 
    path: auction-contract-setup
  - name: 4.2 ERC721 Auction - Start and Bid Functions
    path: auction-start-bid
  - name: 4.3 ERC721 Auction - Withdraw and End Functions
    path: auction-withdraw-end