--- 
id: Contracts - NFT Auction
name: NFT Course
summary: Learn how to write an ERC721 (NFT) auction contract. Developed by the p2p learning platform https://dacade.org.
level: 2
tags: 
  - Solidity
  - Tokens
  - NFT
  - Contracts
steps:
  - name: Contract Setup 
    path: auction-contract-setup
  - name: Start and Bid Functions
    path: auction-start-bid
  - name: Withdraw and End Functions
    path: auction-withdraw-end